[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]  # for all targets

[dependencies]
serde = { version = "1.0", features = ["derive"] }
flutter_rust_bridge = "=2.11.1"           
tokio = { version = "1", features = ["rt"] }
anyhow = "1.0"