name: Build Android (Portalis)
description: Build Android JNI libs + APK and upload artifact
inputs:
  working-dir:
    description: Path to Flutter project
    required: false
    default: portalis
runs:
  using: composite
  steps:
    - name: Compute metadata
      id: meta
      shell: bash
      run: |
        echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
        echo "run_date=$(date -u +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Toolchains
      id: setup
      uses: ./.github/actions/setup-flutter-rust
      with:
        rust-targets: >-
          aarch64-linux-android x86_64-linux-android armv7-linux-androideabi
        install-cargo-ndk: 'true'
        cache-key-suffix: android
        extract-version: 'true'
        extract-backend-version: 'true'
        working-dir: ${{ inputs.working-dir }}

    - name: Build Rust JNI libs (release)
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: bash ./android/build_rust_android.sh release

    - name: Flutter build apk (release)
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: flutter build apk --release

    - name: Upload apk
      uses: actions/upload-artifact@v4
      with:
        name: Portalis-${{ steps.setup.outputs.backend-version }}-Android-${{ steps.setup.outputs.app-version }}-${{ steps.meta.outputs.short_sha }}-release
        path: ${{ inputs.working-dir }}/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 1
